# Generated by Django 5.1.7 on 2025-06-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskharu', models.CharField(max_length=40)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
