# Generated by Django 5.1.7 on 2025-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskss_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskss',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
